// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CamIPStore.DB.Migrations
{
    [DbContext(typeof(IPShopDBContext))]
    partial class IPShopDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Camera", b =>
                {
                    b.Property<int>("IdCam")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdCam")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AmThanh")
                        .HasColumnName("AmThanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CamBien")
                        .HasColumnName("CamBien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CoDay")
                        .HasColumnName("CoDay")
                        .HasColumnType("bit");

                    b.Property<bool>("DKTuXa")
                        .HasColumnName("DieuKhiTuXa")
                        .HasColumnType("bit");

                    b.Property<string>("DoPhanGiai")
                        .HasColumnName("DoPhanGiai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoXoayDoc")
                        .HasColumnName("DoXoayDoc")
                        .HasColumnType("int");

                    b.Property<int>("DoXoayNgang")
                        .HasColumnName("DoXoayNgang")
                        .HasColumnType("int");

                    b.Property<string>("DungLuong")
                        .HasColumnName("DungLuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("GiaBan")
                        .HasColumnName("GiaBan")
                        .HasColumnType("real");

                    b.Property<float>("GiaGoc")
                        .HasColumnName("GiaGoc")
                        .HasColumnType("real");

                    b.Property<int>("IdNSX")
                        .HasColumnName("IdNSX")
                        .HasColumnType("int");

                    b.Property<string>("KhoangCach")
                        .HasColumnName("KhoangCach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("KhongDay")
                        .HasColumnName("KhongDay")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasColumnName("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnName("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnName("TenCamera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XuatXu")
                        .HasColumnName("XuatXu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCam");

                    b.HasIndex("IdNSX");

                    b.ToTable("Camera");

                    b.HasData(
                        new
                        {
                            IdCam = 1,
                            AmThanh = "Đàm thoại 2 chiều",
                            CamBien = "Báo động khi có người đột nhập.",
                            CoDay = true,
                            DKTuXa = true,
                            DoPhanGiai = "Hình ảnh sắc nét HD - 720p.",
                            DoXoayDoc = 180,
                            DoXoayNgang = 360,
                            DungLuong = "max 64G",
                            GiaBan = 7000000f,
                            GiaGoc = 7000000f,
                            IdNSX = 1,
                            KhoangCach = "",
                            KhongDay = true,
                            MoTa = "",
                            SoLuong = 90,
                            Ten = "Camera Wifi Không dây Yoosee 3 Râu 720p",
                            XuatXu = "Trung Quốc"
                        },
                        new
                        {
                            IdCam = 2,
                            AmThanh = "Đàm thoại 2 chiều",
                            CamBien = "Phát hiển chuyển động",
                            CoDay = false,
                            DKTuXa = true,
                            DoPhanGiai = "Full HD (1080p)",
                            DoXoayDoc = 180,
                            DoXoayNgang = 360,
                            DungLuong = "64 GB",
                            GiaBan = 4900000f,
                            GiaGoc = 4900000f,
                            IdNSX = 3,
                            KhoangCach = "10m trong tối",
                            KhongDay = true,
                            MoTa = "",
                            SoLuong = 89,
                            Ten = "Camera IP Mi Home 360 Độ 1080P Xiaomi BHR4885GL",
                            XuatXu = "Trung Quốc"
                        },
                        new
                        {
                            IdCam = 3,
                            AmThanh = "Đàm thoại 2 chiều, tích hợp còi thông báo",
                            CamBien = "Phát hiển chuyển động",
                            CoDay = false,
                            DKTuXa = true,
                            DoPhanGiai = "2304 × 1296 2K",
                            DoXoayDoc = 180,
                            DoXoayNgang = 360,
                            DungLuong = "MicroSD <= 256GB",
                            GiaBan = 5600000f,
                            GiaGoc = 5600000f,
                            IdNSX = 3,
                            KhoangCach = "10m trong tối",
                            KhongDay = true,
                            MoTa = "",
                            SoLuong = 67,
                            Ten = "Camera IP Mi Home 360 Độ 2K Pro Xiaomi BHR4193GL",
                            XuatXu = "Trung Quốc"
                        },
                        new
                        {
                            IdCam = 4,
                            AmThanh = "Đàm thoại 2 chiều nhờ trang bị micro và loa tích hợp",
                            CamBien = "Gửi thông báo đến bạn ngay khi phát hiện chuyển động.",
                            CoDay = true,
                            DKTuXa = true,
                            DoPhanGiai = "3MP (2048 x 1536)",
                            DoXoayDoc = 180,
                            DoXoayNgang = 360,
                            DungLuong = "MicroSD ≤ 128GB (15-20 ngày)",
                            GiaBan = 3900000f,
                            GiaGoc = 3900000f,
                            IdNSX = 5,
                            KhoangCach = "30 m trong tối",
                            KhongDay = true,
                            MoTa = "",
                            SoLuong = 96,
                            Ten = "Thông số kỹ thuật Camera IP Ngoài Trời 3MP TP-link Tapo C310 Trắng",
                            XuatXu = "Trung Quốc"
                        },
                        new
                        {
                            IdCam = 5,
                            AmThanh = "Tính năng Talkback (âm thanh 2 chiều)",
                            CamBien = "",
                            CoDay = false,
                            DKTuXa = true,
                            DoPhanGiai = "2304 × 1296 2K",
                            DoXoayDoc = 108,
                            DoXoayNgang = 360,
                            DungLuong = "MicroSD ≤ 32GB (4-5 ngày)",
                            GiaBan = 800000f,
                            GiaGoc = 800000f,
                            IdNSX = 2,
                            KhoangCach = "10 m trong tối",
                            KhongDay = true,
                            MoTa = "",
                            SoLuong = 99,
                            Ten = "Camera IP Mi Home 360 Độ 2K Xiaomi BHR4457GL",
                            XuatXu = "Trung Quốc"
                        },
                        new
                        {
                            IdCam = 6,
                            AmThanh = "loa ngoài và micrô tích hợp.",
                            CamBien = "",
                            CoDay = true,
                            DKTuXa = true,
                            DoPhanGiai = "Full HD 1080p",
                            DoXoayDoc = 0,
                            DoXoayNgang = 0,
                            DungLuong = "MicroSD ≤ 128GB (15-20 ngày)",
                            GiaBan = 8900000f,
                            GiaGoc = 8900000f,
                            IdNSX = 2,
                            KhoangCach = "9 m trong tối",
                            KhongDay = false,
                            MoTa = "",
                            SoLuong = 12,
                            Ten = "Camera IP 1080P TP-Link Tapo TC60 Trắng",
                            XuatXu = "Trung Quốc"
                        },
                        new
                        {
                            IdCam = 7,
                            AmThanh = "",
                            CamBien = "1/3\" 3.0 Megapixel",
                            CoDay = true,
                            DKTuXa = true,
                            DoPhanGiai = "20fps@3Mp(2048×1536) & 25/30fps@2.0Mp(1920×1080)",
                            DoXoayDoc = 0,
                            DoXoayNgang = 0,
                            DungLuong = "",
                            GiaBan = 2700000f,
                            GiaGoc = 2700000f,
                            IdNSX = 6,
                            KhoangCach = "30m",
                            KhongDay = false,
                            MoTa = "",
                            SoLuong = 97,
                            Ten = "Camera KBVISION KX-Y3002N 3.0 megapixel, tầm xa hồng ngoại 30m, cảm biến ngày/đêm, chuẩn IP67",
                            XuatXu = "Trung Quốc"
                        },
                        new
                        {
                            IdCam = 8,
                            AmThanh = "Trò chuyện hai chiều",
                            CamBien = "CMOS Quét liên tục 1/4”",
                            CoDay = true,
                            DKTuXa = true,
                            DoPhanGiai = "1080p",
                            DoXoayDoc = 55,
                            DoXoayNgang = 340,
                            DungLuong = "Khe cắm thẻ MicroSD (lên tới 256 GB)",
                            GiaBan = 2200000f,
                            GiaGoc = 2200000f,
                            IdNSX = 5,
                            KhoangCach = "lên tới 10m/33ft",
                            KhongDay = true,
                            MoTa = "",
                            SoLuong = 26,
                            Ten = "Camera IP Wifi Ezviz C6N 1080p",
                            XuatXu = "Trung Quốc"
                        },
                        new
                        {
                            IdCam = 9,
                            AmThanh = "Microphone tích hợp",
                            CamBien = "HD 2.0MPx CMOS",
                            CoDay = true,
                            DKTuXa = true,
                            DoPhanGiai = "",
                            DoXoayDoc = 100,
                            DoXoayNgang = 350,
                            DungLuong = "64GB",
                            GiaBan = 8300000f,
                            GiaGoc = 8300000f,
                            IdNSX = 5,
                            KhoangCach = "10m",
                            KhongDay = true,
                            MoTa = "",
                            SoLuong = 62,
                            Ten = "CAMERA PTZ NGOÀI TRỜI 2.0 ,KÈM THẺ NHỚ 64G",
                            XuatXu = "Trung Quốc"
                        },
                        new
                        {
                            IdCam = 10,
                            AmThanh = "Đàm thoại 2 chiều",
                            CamBien = "Cảnh báo khi có người đột nhập.",
                            CoDay = true,
                            DKTuXa = true,
                            DoPhanGiai = "Hình ảnh sắc nét HD – 720p.",
                            DoXoayDoc = 120,
                            DoXoayNgang = 355,
                            DungLuong = "Micro SD(tối đa 128GB)",
                            GiaBan = 9200000f,
                            GiaGoc = 9200000f,
                            IdNSX = 1,
                            KhoangCach = "10m trong tối",
                            KhongDay = true,
                            MoTa = "",
                            SoLuong = 20,
                            Ten = "Camera Ip Wifi Carecam XF2-200 720p",
                            XuatXu = "Trung Quốc"
                        },
                        new
                        {
                            IdCam = 11,
                            AmThanh = "Đàm thoại 2 chiều",
                            CamBien = "1/2.8\" CMOS",
                            CoDay = true,
                            DKTuXa = true,
                            DoPhanGiai = "1080p",
                            DoXoayDoc = 100,
                            DoXoayNgang = 360,
                            DungLuong = "MicroSD (tối đa 256GB)",
                            GiaBan = 4700000f,
                            GiaGoc = 4700000f,
                            IdNSX = 6,
                            KhoangCach = "30m trong tối",
                            KhongDay = true,
                            MoTa = "",
                            SoLuong = 15,
                            Ten = "Camera IP Wifi HILook IPC-B120W 1080P",
                            XuatXu = "Trung Quốc"
                        },
                        new
                        {
                            IdCam = 12,
                            AmThanh = "Đàm thoại 2 chiều, khử ồn tốt",
                            CamBien = "Cảnh báo khi có người đột nhập.",
                            CoDay = false,
                            DKTuXa = true,
                            DoPhanGiai = "1080p",
                            DoXoayDoc = 109,
                            DoXoayNgang = 350,
                            DungLuong = "Micro SD(tối đa 128GB)",
                            GiaBan = 7900000f,
                            GiaGoc = 7900000f,
                            IdNSX = 4,
                            KhoangCach = "10m trong tối",
                            KhongDay = true,
                            MoTa = "",
                            SoLuong = 50,
                            Ten = "Camera IP không dây Ebitcam EBF4 1080P",
                            XuatXu = "Trung Quốc"
                        },
                        new
                        {
                            IdCam = 13,
                            AmThanh = "Đàm thoại 2 chiều",
                            CamBien = "Cảnh báo chuyển động",
                            CoDay = true,
                            DKTuXa = true,
                            DoPhanGiai = "1080p",
                            DoXoayDoc = 110,
                            DoXoayNgang = 95,
                            DungLuong = "MicroSD (tối đa 256GB)",
                            GiaBan = 2800000f,
                            GiaGoc = 2800000f,
                            IdNSX = 2,
                            KhoangCach = "30m trong tối",
                            KhongDay = true,
                            MoTa = "",
                            SoLuong = 58,
                            Ten = "Camera ip Wifi Ezviz C3WN CS-CV310 1080P ",
                            XuatXu = "Trung Quốc"
                        },
                        new
                        {
                            IdCam = 14,
                            AmThanh = "Đàm thoại 2 chiều",
                            CamBien = "1/4 CMOS",
                            CoDay = false,
                            DKTuXa = true,
                            DoPhanGiai = "2MP :720P(1280*720)",
                            DoXoayDoc = 110,
                            DoXoayNgang = 360,
                            DungLuong = "Micro SD(tối đa 128GB)",
                            GiaBan = 8500000f,
                            GiaGoc = 8500000f,
                            IdNSX = 1,
                            KhoangCach = "20m trong tối",
                            KhongDay = true,
                            MoTa = "",
                            SoLuong = 26,
                            Ten = "Camera Ip wifi quay 360 độ cao cấp hãng ORIKON",
                            XuatXu = "Trung Quốc"
                        },
                        new
                        {
                            IdCam = 15,
                            AmThanh = "Tích hợp micro: nghe đc âm thanh khi xem",
                            CamBien = "cảnh báo cho người dùng khi có chuyển động",
                            CoDay = true,
                            DKTuXa = true,
                            DoPhanGiai = "2304p x 1296P",
                            DoXoayDoc = 120,
                            DoXoayNgang = 360,
                            DungLuong = "MicroSD (tối đa 256GB)",
                            GiaBan = 5200000f,
                            GiaGoc = 5200000f,
                            IdNSX = 6,
                            KhoangCach = "20m trong tối",
                            KhongDay = true,
                            MoTa = "",
                            SoLuong = 97,
                            Ten = "Camera IP WIFI trong nhà YooSee New 2020 ( 3 anten Full HD 1080P)",
                            XuatXu = "Trung Quốc"
                        },
                        new
                        {
                            IdCam = 16,
                            AmThanh = "Tích hợp micro: nghe đc âm thanh khi xem",
                            CamBien = "",
                            CoDay = false,
                            DKTuXa = true,
                            DoPhanGiai = "2304P x 1296P - 3.0mpx Siêu nét",
                            DoXoayDoc = 180,
                            DoXoayNgang = 360,
                            DungLuong = "MicroSD (tối đa 256GB)",
                            GiaBan = 7600000f,
                            GiaGoc = 7600000f,
                            IdNSX = 1,
                            KhoangCach = "30m trong tối",
                            KhongDay = true,
                            MoTa = "",
                            SoLuong = 80,
                            Ten = "Camera YooSee thế hệ mới - 3.0mpx",
                            XuatXu = "Trung Quốc"
                        },
                        new
                        {
                            IdCam = 17,
                            AmThanh = "Đàm thoại 2 chiều. ️",
                            CamBien = "Cảnh báo chuyển động",
                            CoDay = true,
                            DKTuXa = true,
                            DoPhanGiai = "3.0Mpx ️",
                            DoXoayDoc = 120,
                            DoXoayNgang = 355,
                            DungLuong = "128Gb.",
                            GiaBan = 3000000f,
                            GiaGoc = 3000000f,
                            IdNSX = 5,
                            KhoangCach = "30m trong tối",
                            KhongDay = true,
                            MoTa = "",
                            SoLuong = 30,
                            Ten = "Camera wifi ngoài trời xoay 360 chống nước CARECAM CC8031",
                            XuatXu = "Trung Quốc"
                        },
                        new
                        {
                            IdCam = 18,
                            AmThanh = "Đàm thoại 2 chiều. ️",
                            CamBien = "Phát hiện chuyển động. Báo động qua điện thoại khi kẻ lạ xâm nhập",
                            CoDay = true,
                            DKTuXa = true,
                            DoPhanGiai = "2.0 MP (1920 x 1080P)",
                            DoXoayDoc = 120,
                            DoXoayNgang = 360,
                            DungLuong = "128GB",
                            GiaBan = 1300000f,
                            GiaGoc = 1300000f,
                            IdNSX = 3,
                            KhoangCach = "10m trong tối",
                            KhongDay = true,
                            MoTa = "",
                            SoLuong = 32,
                            Ten = "Carecam IP Ngoài Tròi 62DK200 ",
                            XuatXu = "Trung Quốc"
                        },
                        new
                        {
                            IdCam = 19,
                            AmThanh = "Đàm thoại 2 chiều. ️",
                            CamBien = "1/2 CMOS",
                            CoDay = true,
                            DKTuXa = true,
                            DoPhanGiai = "2.0M Full HD 1080P",
                            DoXoayDoc = 120,
                            DoXoayNgang = 360,
                            DungLuong = "128GB",
                            GiaBan = 1900000f,
                            GiaGoc = 1900000f,
                            IdNSX = 6,
                            KhoangCach = "10m trong tối",
                            KhongDay = true,
                            MoTa = "",
                            SoLuong = 65,
                            Ten = "Camera Mini IP Vstarcam CB72 1080P 2.0 Sim 4G LTE Giám Sát Hành Trình Ô Tô",
                            XuatXu = "Trung Quốc"
                        },
                        new
                        {
                            IdCam = 20,
                            AmThanh = "Đàm thoại 2 chiều. ️",
                            CamBien = "Cảnh báo chuyển động",
                            CoDay = false,
                            DKTuXa = true,
                            DoPhanGiai = "1080p",
                            DoXoayDoc = 120,
                            DoXoayNgang = 360,
                            DungLuong = "MicroSD (hỗ trợ tối thiểu 16GB, tối đa 64GB)",
                            GiaBan = 6300000f,
                            GiaGoc = 6300000f,
                            IdNSX = 2,
                            KhoangCach = "10m trong tối",
                            KhongDay = true,
                            MoTa = "",
                            SoLuong = 96,
                            Ten = "Camera IP thông minh Xiaomi Mijia Basic 1080p QDJ4047GL",
                            XuatXu = "Trung Quốc"
                        },
                        new
                        {
                            IdCam = 21,
                            AmThanh = "Đàm thoại 2 chiều. ️",
                            CamBien = "Cảnh báo chuyển động",
                            CoDay = true,
                            DKTuXa = true,
                            DoPhanGiai = "FullHD 1080",
                            DoXoayDoc = 120,
                            DoXoayNgang = 360,
                            DungLuong = "Micro SD, Max 256 GB",
                            GiaBan = 5800000f,
                            GiaGoc = 5800000f,
                            IdNSX = 4,
                            KhoangCach = "10m trong tối",
                            KhongDay = true,
                            MoTa = "",
                            SoLuong = 77,
                            Ten = "Camera IP WIFI IMOU RANGER 2 IPC - A22EP Full HD 1080P",
                            XuatXu = "Trung Quốc"
                        },
                        new
                        {
                            IdCam = 22,
                            AmThanh = "Micro chất lượng cao, đảm bảo âm thanh thu được rõ ràng.",
                            CamBien = "Cảnh báo chuyển động",
                            CoDay = true,
                            DKTuXa = true,
                            DoPhanGiai = "FullHD 1080",
                            DoXoayDoc = 90,
                            DoXoayNgang = 90,
                            DungLuong = "Micro SD, Max 256 GB",
                            GiaBan = 3300000f,
                            GiaGoc = 3300000f,
                            IdNSX = 3,
                            KhoangCach = "30m trong tối",
                            KhongDay = true,
                            MoTa = "",
                            SoLuong = 12,
                            Ten = "Camera IP Wifi Ngoài Trời Imou F22FP Bullet 2E Full HD 1080P CÓ MÀU BAN ĐÊM ,KÈM PHÍCH CẮM ÂM",
                            XuatXu = "Trung Quốc"
                        },
                        new
                        {
                            IdCam = 23,
                            AmThanh = "Đàm thoại 2 chiều. ️",
                            CamBien = "1/4 CMOS",
                            CoDay = false,
                            DKTuXa = true,
                            DoPhanGiai = "1080p",
                            DoXoayDoc = 55,
                            DoXoayNgang = 340,
                            DungLuong = "MicroSD (lên tới 256 GB)",
                            GiaBan = 6400000f,
                            GiaGoc = 6400000f,
                            IdNSX = 2,
                            KhoangCach = "Tầm nhìn ban đêm thông minh với Smart IR (lên tới 10m/33ft.)",
                            KhongDay = true,
                            MoTa = "",
                            SoLuong = 62,
                            Ten = "Camera IP Wifi Ezviz C6N 2MPX",
                            XuatXu = "Trung Quốc"
                        },
                        new
                        {
                            IdCam = 24,
                            AmThanh = "Đàm thoại 2 chiều. ️",
                            CamBien = "Cảnh báo chuyển động",
                            CoDay = false,
                            DKTuXa = true,
                            DoPhanGiai = "FullHD 1080",
                            DoXoayDoc = 90,
                            DoXoayNgang = 0,
                            DungLuong = "Micro SD, Max 256 GB",
                            GiaBan = 7000000f,
                            GiaGoc = 7000000f,
                            IdNSX = 6,
                            KhoangCach = "10m trong tối",
                            KhongDay = true,
                            MoTa = "",
                            SoLuong = 4,
                            Ten = "Camera ip wifi mini V380 Pro - Hỗ trợ xem hồng ngoại ban đêm",
                            XuatXu = "Trung Quốc"
                        });
                });

            modelBuilder.Entity("Entities.ChiTietHoaDon", b =>
                {
                    b.Property<int>("IdCam")
                        .HasColumnName("IdCam")
                        .HasColumnType("int");

                    b.Property<int>("IdHD")
                        .HasColumnName("IdHD")
                        .HasColumnType("int");

                    b.Property<float>("GiaBan")
                        .HasColumnName("GiaBan")
                        .HasColumnType("real");

                    b.Property<int>("SLMua")
                        .HasColumnName("SoLuongMua")
                        .HasColumnType("int");

                    b.HasKey("IdCam", "IdHD");

                    b.HasIndex("IdHD");

                    b.ToTable("ChiTietHoaDon");

                    b.HasData(
                        new
                        {
                            IdCam = 1,
                            IdHD = 1,
                            GiaBan = 123000f,
                            SLMua = 1
                        });
                });

            modelBuilder.Entity("Entities.ChiTietKhuyenMai", b =>
                {
                    b.Property<int>("IdCam")
                        .HasColumnName("IdCam")
                        .HasColumnType("int");

                    b.Property<int>("IdKM")
                        .HasColumnName("IdKM")
                        .HasColumnType("int");

                    b.HasKey("IdCam", "IdKM");

                    b.HasIndex("IdKM");

                    b.ToTable("ChiTietKhuyenMai");

                    b.HasData(
                        new
                        {
                            IdCam = 1,
                            IdKM = 1
                        });
                });

            modelBuilder.Entity("Entities.GioHang", b =>
                {
                    b.Property<int>("IdCam")
                        .HasColumnName("IdCam")
                        .HasColumnType("int");

                    b.Property<int>("IdTK")
                        .HasColumnName("IdTK")
                        .HasColumnType("int");

                    b.Property<int>("Sl")
                        .HasColumnName("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IdCam", "IdTK");

                    b.HasIndex("IdTK");

                    b.ToTable("GioHang");

                    b.HasData(
                        new
                        {
                            IdCam = 1,
                            IdTK = 1,
                            Sl = 1
                        });
                });

            modelBuilder.Entity("Entities.Hinh", b =>
                {
                    b.Property<int>("IdHinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdHinh")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("HinhDaiDien")
                        .HasColumnName("HinhDaiDien")
                        .HasColumnType("bit");

                    b.Property<int>("IdCam")
                        .HasColumnName("IdCam")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .HasColumnName("Link")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHinh");

                    b.HasIndex("IdCam");

                    b.ToTable("Hinh");

                    b.HasData(
                        new
                        {
                            IdHinh = 1,
                            HinhDaiDien = true,
                            IdCam = 1,
                            Link = ""
                        });
                });

            modelBuilder.Entity("Entities.HoaDon", b =>
                {
                    b.Property<int>("IdHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdHD")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTK")
                        .HasColumnName("IdTK")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnName("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<float>("TongGia")
                        .HasColumnName("TongGia")
                        .HasColumnType("real");

                    b.Property<int>("TrangThai")
                        .HasColumnName("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdHD");

                    b.HasIndex("IdTK");

                    b.ToTable("HoaDon");

                    b.HasData(
                        new
                        {
                            IdHD = 1,
                            GhiChu = "",
                            IdTK = 1,
                            NgayTao = new DateTime(2021, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TongGia = 123000f,
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("Entities.KhuyenMai", b =>
                {
                    b.Property<int>("IdKM")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdKM")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Banner")
                        .HasColumnName("Banner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DenNgay")
                        .HasColumnName("DenNgay")
                        .HasColumnType("datetime");

                    b.Property<int>("PhanTramGiam")
                        .HasColumnName("PhanTramGiam")
                        .HasColumnType("int");

                    b.Property<string>("TenKM")
                        .IsRequired()
                        .HasColumnName("TenKM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TuNgay")
                        .HasColumnName("TuNgay")
                        .HasColumnType("datetime");

                    b.HasKey("IdKM");

                    b.ToTable("KhuyenMai");

                    b.HasData(
                        new
                        {
                            IdKM = 1,
                            Banner = "",
                            DenNgay = new DateTime(2021, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhanTramGiam = 25,
                            TenKM = "Flash Sale cuối tuần",
                            TuNgay = new DateTime(2021, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdKM = 2,
                            Banner = "",
                            DenNgay = new DateTime(2021, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhanTramGiam = 25,
                            TenKM = "Tháng 6 Vui Vẻ",
                            TuNgay = new DateTime(2021, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdKM = 3,
                            Banner = "",
                            DenNgay = new DateTime(2021, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhanTramGiam = 45,
                            TenKM = "Khai trương",
                            TuNgay = new DateTime(2021, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdKM = 4,
                            Banner = "",
                            DenNgay = new DateTime(2021, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhanTramGiam = 25,
                            TenKM = "Ưu đãi khách mới",
                            TuNgay = new DateTime(2021, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdKM = 5,
                            Banner = "",
                            DenNgay = new DateTime(2021, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhanTramGiam = 15,
                            TenKM = "Ưu đãi tân sinh viên",
                            TuNgay = new DateTime(2021, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdKM = 6,
                            Banner = "",
                            DenNgay = new DateTime(2021, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhanTramGiam = 25,
                            TenKM = "Sinh nhật vui vẻ",
                            TuNgay = new DateTime(2021, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.NhaSanXuat", b =>
                {
                    b.Property<int>("IdNSX")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdNSX")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenNSX")
                        .IsRequired()
                        .HasColumnName("TenNSX")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNSX");

                    b.ToTable("NhaSanXuat");

                    b.HasData(
                        new
                        {
                            IdNSX = 1,
                            TenNSX = "Xiaomi"
                        },
                        new
                        {
                            IdNSX = 2,
                            TenNSX = "TP-Link"
                        },
                        new
                        {
                            IdNSX = 3,
                            TenNSX = "EZVIZ - HIKVISION"
                        },
                        new
                        {
                            IdNSX = 4,
                            TenNSX = "Kbvision"
                        },
                        new
                        {
                            IdNSX = 5,
                            TenNSX = "Yoosee"
                        },
                        new
                        {
                            IdNSX = 6,
                            TenNSX = "CareCam"
                        });
                });

            modelBuilder.Entity("Entities.TaiKhoan", b =>
                {
                    b.Property<int>("IdTK")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdTK")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnName("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnName("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnName("MatKhau")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<bool>("QuyenSD")
                        .HasColumnName("QuyenSD")
                        .HasColumnType("bit");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnName("SDT")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("TenTK")
                        .IsRequired()
                        .HasColumnName("TenTK")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<bool>("TrangThai")
                        .HasColumnName("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdTK");

                    b.ToTable("TaiKhoan");

                    b.HasData(
                        new
                        {
                            IdTK = 1,
                            DiaChi = "Cần Thơ",
                            Email = "Hieu@gmail.com",
                            HoTen = "Trần Nguyễn Minh Hiếu",
                            MatKhau = "12345",
                            QuyenSD = true,
                            SDT = "0253737775",
                            TenTK = "user1",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 2,
                            DiaChi = "Cần Thơ",
                            Email = "Binh@abc.xyz",
                            HoTen = "Ngô Minh Bình",
                            MatKhau = "12345",
                            QuyenSD = true,
                            SDT = "0162332975",
                            TenTK = "user2",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 3,
                            DiaChi = "Cần Thơ",
                            Email = "Nga@cpm.ebc.cit",
                            HoTen = "Huỳnh Thảo Nga",
                            MatKhau = "12345",
                            QuyenSD = false,
                            SDT = "0940895982",
                            TenTK = "user3",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 4,
                            DiaChi = "Cần Thơ",
                            Email = "Duong@gmail.com",
                            HoTen = "Lưu Tường Dương",
                            MatKhau = "12345",
                            QuyenSD = false,
                            SDT = "0486695231",
                            TenTK = "user4",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 5,
                            DiaChi = "Cần Thơ",
                            Email = "Nga@gmail.com.vn",
                            HoTen = "Nguyễn Trần Kim Nga",
                            MatKhau = "12345",
                            QuyenSD = true,
                            SDT = "0462578910",
                            TenTK = "user5",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 6,
                            DiaChi = "Cần Thơ",
                            Email = "Linh@gmail.com.vn",
                            HoTen = "Lưu Mỹ Linh",
                            MatKhau = "12345",
                            QuyenSD = false,
                            SDT = "0976937303",
                            TenTK = "user6",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 7,
                            DiaChi = "Cần Thơ",
                            Email = "Ngan@gmail.com.vn",
                            HoTen = "Hồ Trung Ngân",
                            MatKhau = "12345",
                            QuyenSD = false,
                            SDT = "0435108713",
                            TenTK = "user7",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 8,
                            DiaChi = "Cần Thơ",
                            Email = "Hao@cpm.ebc.cit",
                            HoTen = "Trần Nguyễn Thanh Hảo",
                            MatKhau = "12345",
                            QuyenSD = true,
                            SDT = "0821802554",
                            TenTK = "user8",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 9,
                            DiaChi = "Cần Thơ",
                            Email = "Gia@cpm.ebc.cit",
                            HoTen = "Ngô Gia",
                            MatKhau = "12345",
                            QuyenSD = false,
                            SDT = "0292595095",
                            TenTK = "user9",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 10,
                            DiaChi = "Cần Thơ",
                            Email = "Ha@yahoo.com",
                            HoTen = "Vi Mỹ Hà",
                            MatKhau = "12345",
                            QuyenSD = false,
                            SDT = "0617426056",
                            TenTK = "user10",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 11,
                            DiaChi = "Cần Thơ",
                            Email = "Lan@gmail.com.vn",
                            HoTen = "Vi Minh Lan",
                            MatKhau = "12345",
                            QuyenSD = false,
                            SDT = "0832714516",
                            TenTK = "user11",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 12,
                            DiaChi = "Cần Thơ",
                            Email = "Hau@abc.xyz",
                            HoTen = "Mai Hậu",
                            MatKhau = "12345",
                            QuyenSD = true,
                            SDT = "0154248463",
                            TenTK = "user12",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 13,
                            DiaChi = "Cần Thơ",
                            Email = "Binh@gmail.com",
                            HoTen = "Ngô Huỳnh Bình",
                            MatKhau = "12345",
                            QuyenSD = false,
                            SDT = "0215600590",
                            TenTK = "user13",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 14,
                            DiaChi = "Cần Thơ",
                            Email = "Dao@gmail.com.vn",
                            HoTen = "Mai Minh Dao",
                            MatKhau = "12345",
                            QuyenSD = true,
                            SDT = "0871156817",
                            TenTK = "user14",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 15,
                            DiaChi = "Cần Thơ",
                            Email = "Dao@gmail.com.vn",
                            HoTen = "Lê Thanh Dao",
                            MatKhau = "12345",
                            QuyenSD = false,
                            SDT = "0545362661",
                            TenTK = "user15",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 16,
                            DiaChi = "Cần Thơ",
                            Email = "Bao@gmail.com",
                            HoTen = "Đỗ Cẩm Bảo",
                            MatKhau = "12345",
                            QuyenSD = false,
                            SDT = "0309659439",
                            TenTK = "user16",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 17,
                            DiaChi = "Cần Thơ",
                            Email = "Dao@yahoo.com",
                            HoTen = "Hồ Kim Dao",
                            MatKhau = "12345",
                            QuyenSD = false,
                            SDT = "0919491248",
                            TenTK = "user17",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 18,
                            DiaChi = "Cần Thơ",
                            Email = "Cong@abc.xyz",
                            HoTen = "Trần Minh Công",
                            MatKhau = "12345",
                            QuyenSD = true,
                            SDT = "0986292715",
                            TenTK = "user18",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 19,
                            DiaChi = "Cần Thơ",
                            Email = "Lan@gmail.com",
                            HoTen = "Nguyễn Trần Mỹ Lan",
                            MatKhau = "12345",
                            QuyenSD = false,
                            SDT = "0807155376",
                            TenTK = "user19",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 20,
                            DiaChi = "Cần Thơ",
                            Email = "Ngoc@cpm.ebc.cit",
                            HoTen = "Huỳnh Trung Ngọc",
                            MatKhau = "12345",
                            QuyenSD = false,
                            SDT = "0176530779",
                            TenTK = "user20",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 21,
                            DiaChi = "Cần Thơ",
                            Email = "Dat@yahoo.com",
                            HoTen = "Trần Nguyễn Huỳnh Đạt",
                            MatKhau = "12345",
                            QuyenSD = false,
                            SDT = "0696679759",
                            TenTK = "user21",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 22,
                            DiaChi = "Cần Thơ",
                            Email = "Hau@yahoo.com",
                            HoTen = "Nguyễn Phúc Thảo Hậu",
                            MatKhau = "12345",
                            QuyenSD = true,
                            SDT = "0699527986",
                            TenTK = "user22",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 23,
                            DiaChi = "Cần Thơ",
                            Email = "Dat@gmail.com",
                            HoTen = "Ngô Đạt",
                            MatKhau = "12345",
                            QuyenSD = true,
                            SDT = "0882101189",
                            TenTK = "user23",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 24,
                            DiaChi = "Cần Thơ",
                            Email = "An@abc.xyz",
                            HoTen = "Hồ Thị Tường An",
                            MatKhau = "12345",
                            QuyenSD = true,
                            SDT = "0674060358",
                            TenTK = "user24",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 25,
                            DiaChi = "Cần Thơ",
                            Email = "Manh@yahoo.com",
                            HoTen = "Mai Cẩm Mạnh",
                            MatKhau = "12345",
                            QuyenSD = false,
                            SDT = "0355909778",
                            TenTK = "user25",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 26,
                            DiaChi = "Cần Thơ",
                            Email = "Hau@yahoo.com",
                            HoTen = "Huỳnh Kim Hậu",
                            MatKhau = "12345",
                            QuyenSD = true,
                            SDT = "0550851297",
                            TenTK = "user26",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 27,
                            DiaChi = "Cần Thơ",
                            Email = "Hoa@yahoo.com",
                            HoTen = "Lưu Hoàng Hóa",
                            MatKhau = "12345",
                            QuyenSD = true,
                            SDT = "0549183731",
                            TenTK = "user27",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 28,
                            DiaChi = "Cần Thơ",
                            Email = "Binh@cpm.ebc.cit",
                            HoTen = "Trần Nguyễn Tường Bình",
                            MatKhau = "12345",
                            QuyenSD = true,
                            SDT = "0312991267",
                            TenTK = "user28",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 29,
                            DiaChi = "Cần Thơ",
                            Email = "Hanh@cpm.ebc.cit",
                            HoTen = "Lưu Hạnh",
                            MatKhau = "12345",
                            QuyenSD = true,
                            SDT = "0594100321",
                            TenTK = "user29",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 30,
                            DiaChi = "Cần Thơ",
                            Email = "Du@cpm.ebc.cit",
                            HoTen = "Lê Minh Du",
                            MatKhau = "12345",
                            QuyenSD = false,
                            SDT = "0567477781",
                            TenTK = "user30",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 31,
                            DiaChi = "Cần Thơ",
                            Email = "Gia@abc.xyz",
                            HoTen = "Nguyễn Trần Gia",
                            MatKhau = "12345",
                            QuyenSD = true,
                            SDT = "0457173781",
                            TenTK = "user31",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 32,
                            DiaChi = "Cần Thơ",
                            Email = "Ngan@gmail.com",
                            HoTen = "Nguyễn Trần Mộng Ngân",
                            MatKhau = "12345",
                            QuyenSD = true,
                            SDT = "0120750995",
                            TenTK = "user32",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 33,
                            DiaChi = "Cần Thơ",
                            Email = "Long@gmail.com",
                            HoTen = "Đỗ Trung Long",
                            MatKhau = "12345",
                            QuyenSD = true,
                            SDT = "0730168885",
                            TenTK = "user33",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 34,
                            DiaChi = "Cần Thơ",
                            Email = "Hanh@cpm.ebc.cit",
                            HoTen = "Dương Trung Hạnh",
                            MatKhau = "12345",
                            QuyenSD = true,
                            SDT = "0374077585",
                            TenTK = "user34",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 35,
                            DiaChi = "Cần Thơ",
                            Email = "Nga@yahoo.com",
                            HoTen = "Vi Trung Nga",
                            MatKhau = "12345",
                            QuyenSD = true,
                            SDT = "0903639096",
                            TenTK = "user35",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 36,
                            DiaChi = "Cần Thơ",
                            Email = "Manh@yahoo.com",
                            HoTen = "Nguyễn Trần Mộng Mạnh",
                            MatKhau = "12345",
                            QuyenSD = true,
                            SDT = "0146865028",
                            TenTK = "user36",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 37,
                            DiaChi = "Cần Thơ",
                            Email = "Duong@cpm.ebc.cit",
                            HoTen = "Nguyễn Phúc Cẩm Dương",
                            MatKhau = "12345",
                            QuyenSD = true,
                            SDT = "0418281298",
                            TenTK = "user37",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 38,
                            DiaChi = "Cần Thơ",
                            Email = "Hau@yahoo.com",
                            HoTen = "Nguyễn Trần Trung Hậu",
                            MatKhau = "12345",
                            QuyenSD = true,
                            SDT = "0295945376",
                            TenTK = "user38",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 39,
                            DiaChi = "Cần Thơ",
                            Email = "Hien@yahoo.com",
                            HoTen = "Lê Văn Hoàng Hiền",
                            MatKhau = "12345",
                            QuyenSD = true,
                            SDT = "0268072701",
                            TenTK = "user39",
                            TrangThai = true
                        },
                        new
                        {
                            IdTK = 40,
                            DiaChi = "Cần Thơ",
                            Email = "Hung@yahoo.com",
                            HoTen = "Trần Nguyễn Thanh Hùng",
                            MatKhau = "12345",
                            QuyenSD = true,
                            SDT = "0856764439",
                            TenTK = "user40",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("Entities.Camera", b =>
                {
                    b.HasOne("Entities.NhaSanXuat", "NhaSanXuat")
                        .WithMany("DsCamera")
                        .HasForeignKey("IdNSX")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.ChiTietHoaDon", b =>
                {
                    b.HasOne("Entities.Camera", "Camera")
                        .WithMany("DsChiTietHoaDon")
                        .HasForeignKey("IdCam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.HoaDon", "HoaDon")
                        .WithMany("DsChiTietHoaDon")
                        .HasForeignKey("IdHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.ChiTietKhuyenMai", b =>
                {
                    b.HasOne("Entities.Camera", "Camera")
                        .WithMany("DsChiTietKhuyenMai")
                        .HasForeignKey("IdCam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.KhuyenMai", "KhuyenMai")
                        .WithMany("DsChiTietKhuyenMai")
                        .HasForeignKey("IdKM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.GioHang", b =>
                {
                    b.HasOne("Entities.Camera", "Camera")
                        .WithMany("DsGioHang")
                        .HasForeignKey("IdCam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("DsGioHang")
                        .HasForeignKey("IdTK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Hinh", b =>
                {
                    b.HasOne("Entities.Camera", "Camera")
                        .WithMany("DsHinh")
                        .HasForeignKey("IdCam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.HoaDon", b =>
                {
                    b.HasOne("Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("DsHoaDon")
                        .HasForeignKey("IdTK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
